### ISSUE TITLE
Forms submit in Safari.

### ISSUE THREAD

**Issue by Apvaris** [bartverdonck/Sitecore-Forms-Extensions#56] opened 2019-09-09 09:37 UTC
Updates of jquery.unobtrusive-ajax.js for files uploader appends additional field with button value, that`s why zero step of form is returned instead of next|previous page.

line: 191 - execute this line for all browsers, except Safari or look for another solution.

**Comment by bartverdonck** [comment] 2019-10-16 11:35
Closing as a duplicate of issue #50

**Closed by bartverdonck** 2019-10-16 11:35 UTC
Labels: duplicate
