### ISSUE TITLE
HttpContext.Current.Items not able to fetch [(object) "NextFormPage"] in my custom implementation of Show Form Page action

### ISSUE THREAD

**Issue by cutture** [bartverdonck/Sitecore-Forms-Extensions#103] opened 2021-01-04 13:55 UTC
Due to my company restrictions I cannot directly use Form Extensions. I need to implement the Show Form Page action in Form extension. So for this I am trying to use Form Extension source code. For this I have performed below steps.

* I have already ipmlemented ShowFormPageAction, ShowFormPageContext , ShowFormPageData and ShowFormPageNavigationLoader classes in my project under SubmitAction/ShowFormPage
* I have created .config file under include folder with below code

<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/"  xmlns:role="http://www.sitecore.net/xmlconfig/role/">
    <sitecore>
        <pipelines>
           
            <forms.renderForm>
                <processor patch:before="*[1]" type="PCOM.XPS.UI.Foundation.FormExtensions.SubmitActions.ShowFormPage.ShowFormPageNavigationLoader, PCOM.XPS.UI.Foundation.FormExtensions" resolve="true" />
            </forms.renderForm>   
    
        </pipelines>
    </sitecore>
</configuration>

* I have included the ShowFormPage.js as it is under sitecore\shell\client\Applications\FormsBuilder\Layouts\Actions in my sitecore instance and in the VS solution.

* I have created the package of sitecore items sitecore/system/Settings/Forms/Submit Actions/Show Form Page (master database) and /sitecore/client/Applications/FormsBuilder/Components/Layouts/Actions/ShowFormPage (this item as well as all the child items in core database) and installed in my development instance.

* I have correctly chnaged the Model Type in sitecore/system/Settings/Forms/Submit Actions/Show Form Page with the appropriate ShowFormPageAction class in my solution.

* I have built the form as per instructions on http://onelittlespark.bartverdonck.be/sitecoreformsextentions/3.1/contenteditordoc/jumptopage.html

* The form contains two pages. One having just one sinle line text field and Submit buttion with Navigation Step as Submit.

* Actions for the the submit button should be to save the data and Show Form Page.

* The 2nd page can simply have a 'Text' field that says 'Thank-you!!!'

* Add the form to a page

* Load the page, fill in the inputs on the page and submit

* You'll see that the form does not display the 2nd - or 'Thank-You' page. All that displays is the first page, refreshed with no data in the input fields anymore.

* When I tried to debug attaching the process, I found that the ocde is returned from get attribute in ShowFormPageContext . As it is not able to get [(object) "NextFormPage"] from HttpContext.Current.Items. Is there any other setting I am missing. Can you please let me know the reason for this as I need to just implement Show Form Page action from Form Extensions source code.

Expected behavior
I expect the behavior to display the next page.

**Comment by bartverdonck** [comment] 2021-02-27 15:06
Hi, thanks for you question. Unfortunatly I don't have an immediate answer. 
Is your issue still relevant or did you manage to figure it out?
As this is not a bug in the module but a question on how to extract some functionality form the module, I will close this ticket. 
If you still need help on your issue, you can reach out to me on Slack.

**Closed by bartverdonck** 2021-02-27 15:06 UTC
Labels: out of scope
