### ISSUE TITLE
Timeout exception for ReCaptcha v2

### ISSUE THREAD

**Issue by aar-nemetos** [bartverdonck/Sitecore-Forms-Extensions#71] opened 2020-01-09 13:31 UTC
We received a timeout exception each time we try to complete the ReCaptcha. We managed to get it working after we cleared browser cache and cookies, but it only worked for the first time it was completed.

**To Reproduce**
1. Go to http://nemetos.dev.nemetos.com/en/Contact-Test
2. Try to complete the ReCaptcha.
3. The ReCaptcha validation times out.
`anchor?ar=1&k=6LewG80UAAAAAEc9ad-Jaxv3OZEDM2Vd5wNYlvuZ&co=aHR0cDovL25lbWV0b3MuZGV2Lm5lbWV0b3MuY29tOjgw&hl=en&v=eQmzkx3d5dtuXlLOA4pEID3I&size=normal&cb=g5sv7vbx4pq6:1 Uncaught (in promise) Timeout (f)
setTimeout (async)
<computed> @ recaptcha__en.js:147
y @ recaptcha__en.js:115
(anonymous) @ recaptcha__en.js:348
Ws @ recaptcha__en.js:20
N5.next @ recaptcha__en.js:18
(anonymous) @ recaptcha__en.js:18
Dh @ recaptcha__en.js:17
Ps @ recaptcha__en.js:18
vY.send @ recaptcha__en.js:348
s3 @ recaptcha__en.js:363
(anonymous) @ recaptcha__en.js:363
Ws @ recaptcha__en.js:20
N5.throw @ recaptcha__en.js:18
G @ recaptcha__en.js:17
`

**Expected behavior**
The ReCaptcha should display a dialog box or validate.

Note: It is working if we click the 'Send Message' button and then we try to complete the ReCaptcha.

**Comment by bartverdonck** [comment] 2020-06-07 14:44
Hi, 

This looks like a local issue as in general this functionality is working as supposed.

I will close this issue as I cannot reproduce it.

Best regards,

Bart

**Closed by bartverdonck** 2020-06-07 14:44 UTC
Labels: local issue
