### ISSUE TITLE
Forms no longer appear / can't be created after installation

### ISSUE THREAD

**Issue by bgarnier2** [bartverdonck/Sitecore-Forms-Extensions#33] opened 2019-03-14 16:15 UTC
Local environment is Sitecore CMS 9.0 rev 171219 (Update 1).

I downloaded and installed the package Sitecore Forms Extensions-1.8.1.zip

Post deployment I logged into sitecore and looked at my forms.

None of my forms appear any longer. Verified that they exist in my content tree. 
Next I tried to create a new form. The UI updates with the message: 

> The form was not loaded due to an error. 	

Looking in the logs the only issue that I see that may be related is:

>  The standard values field of template /sitecore/templates/System/Forms/Form:{6ABEE1F2-4AB4-47F0-AD8B-BDB36F37F64C} does not contain an ID that points to a child

I checked the documentation site as well as existing open and closed issues and didn't see a related issue.

I can't do any work on forms now. Any suggestions would be welcome.  I intend to inspect the package and try to walk its changes backwards by using files extracted from SIM and packaging up working items from our dev server.

I started by packaging and installing :{6ABEE1F2-4AB4-47F0-AD8B-BDB36F37F64C}  (The Form System Template) from our dev server. I can create forms now but can not view any of the forms that had been previously created.

**Comment by bartverdonck** [comment] 2019-03-15 08:11
Try rebuilding your search indexes. It's a known issue related to forms, not the module.

**Comment by bartverdonck** [comment] 2019-03-15 08:29
Can you see the list of forms? Or does the error occur when editing a form from the list? Try rebuilding your search indexes.

**Comment by bgarnier2** [comment] 2019-03-15 12:54
Hi @bartverdonck ,

The list of forms was visible prior to installation. Post installation it said I have no forms. My first instinct was to rebuild the web & master indexes and did that. It had no effect.

I initially could not create a new form and got the error above. I looked at the Form System Template and found that it no longer had any fields. I packaged and installed the version of that template on our dev server and was able to create new forms again, but still could not view the list of existing ones.

**Comment by bartverdonck** [comment] 2019-03-15 14:23
Strange, looks like something went wrong upon installation. Where you asked to override any items? Did you choose merge-merge? Normally these settings are set on the package, but I might have forgotten it on a source.

**Comment by bartverdonck** [comment] 2019-03-15 14:24
I will try to reproduce on a fresh installation.

**Comment by bgarnier2** [comment] 2019-03-15 14:26
@bartverdonck  

I don't recall but I assume I would have overwritten my local files with yours if prompted. The only other environmental condition that may conflict is that this project is using Unicorn. I'm still new to the project but some external tool that controls template definitions might throw a fly in the ointment maybe?

**Comment by kezhan-ping** [comment] 2019-04-16 06:54
I get the same issue with Sitecore 9.0 update 2. During installation, I chose overwrite when asked by package installation process.

I could see one form after installing (Should have 2 in total), and the thumbnail is missing for some reason. After rebuilding indexes, they are all gone and can't create new forms as well.

However if you have the form editing url, just swap the form id with the id you get from content editor, can still edit the form and the new actions are all working as well after being added to the form. I am trying to restore my dev db and try installing the package again with Merge option.

**Comment by bartverdonck** [comment] 2019-04-16 10:41
Hi, 

In version 1.8 there was I forgot to set the installation options on one of the sources in the package.
This was fixed in version 1.8.1.

Please use version 1.8.1.

Hope this will help you fix the issue.

Best Regards

**Comment by kezhan-ping** [comment] 2019-04-16 10:43
Thanks Bart, from memory I used v1.8.1 because that's newer, but will double check .


Ke Zhan
Senior Developer

PING Works
1-7 Albion Place, Sydney NSW 2000
p: +61 2 9321 1551<tel:+61%202%209321%201551> | www.ping-works.com.au<https://www.ping-works.com.au>
d: +61 2 9321 1563<tel:+61%202%209321%201563>
Download a vCard<https://ping-vcards.azurewebsites.net/api/GenerateVCF?name=>

________________________________

**Comment by kezhan-ping** [comment] 2019-04-18 03:49
Thanks @bartverdonck , 1.8.1 is the version I have used however. And can confirm tried again with Merge-Merge, no issues this time.

**Comment by bartverdonck** [comment] 2019-04-28 12:23
Changed install setting to merge-merge.

**Closed by bartverdonck** 2019-04-28 12:23 UTC
