### ISSUE TITLE
jQuery script error on submit (Edge)

### ISSUE THREAD

**Issue by sreekrishnanks** [bartverdonck/Sitecore-Forms-Extensions#25] opened 2019-02-13 13:13 UTC
**Describe the bug**

The issue relates to the issue #19 
When clicking on the submit button  a JavaScript error occurs in the Internet Explorer and Microsoft Edge browser. The following message is shown in the console of the developer tools:

> SCRIPT438: Object doesn't support property or method 'has'
jquery.unobtrusive-ajax.min.js (1,2917)

**To Reproduce**

1. Use a Sitecore instance with this module installed
2. create a form with a submit button (I have assigned a custom submit action)
3. insert the form into a page
4. open the page in IE or Edge and open the developer tools console
5. click on the submit button and see the error message in the console

**Expected behavior**
Like in any other browser: acting like a form. Reload of the page or execution of any assigned submit action for example.

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Internet Explorer 11 or Microsoft Edge

Thanks in Advance
Sreekrishnna

**Comment by bartverdonck** [comment] 2019-02-17 18:12
Hi Screekrishnna,

I'm currently unsuccessfull at reproducing the issue.

Please provide me the following details:
+ Sitecore Version
+ Version number of the forms extensions module you installed

+ Overview of the fields on your form. (Possibly a screenshot of your form)

**Comment by sreekrishnanks** [comment] 2019-02-18 11:02
Please find the details :
Sitecore Version : Sitecore 9.0 Update 2
Forms extension version : Sitecore Forms Extensions-1.6
Form screenshot : 
![form section 1](https://user-images.githubusercontent.com/8579902/52946712-b79cd680-339a-11e9-8558-2ededad75250.png)
![form section 2](https://user-images.githubusercontent.com/8579902/52946713-b8ce0380-339a-11e9-8e3e-e190d011a82b.png)

**Comment by bartverdonck** [comment] 2019-02-18 18:05
Issue #19 was fixed in version 1.6.2, so it is normal that you still have this issue when using version 1.6.

I have rechecked the code and could find nothing wrong with it since the release of 1.6.2.

This method "has" is also not present anymore in the javascript since 1.6.2

**Closed by bartverdonck** 2019-02-18 18:05 UTC
Labels: could not reproduce, invalid
