### ISSUE TITLE
Error showing confirmation form "page" in form when using recaptcha

### ISSUE THREAD

**Issue by saraharmst** [bartverdonck/Sitecore-Forms-Extensions#65] opened 2019-10-31 06:04 UTC
In sitecore 9.2 when attempting to use a page form element for confirmation, along with a recaptcha field, the original form "page" element reappears reappears after successful submission with a recaptcha error and no recaptcha field showing

**To Reproduce**
1. Create a form with 2 pages included
2. In the first first page add a recaptcha field and a submit button
3. Add a submit action "Show form page" and select your second page
4. Go to the form, tick the recaptcha box
5. Click submit
6. You can see a flash of the thankyou page and then the original form is returned with the recaptcha error (screen recording included in zip in attachments)

**Expected behavior**
I expect the confirmation page to remain shown

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
![Form WIth submit action](https://user-images.githubusercontent.com/6299733/67922955-27917b00-fc11-11e9-9d93-bc3c39c22c9d.PNG)
[ReproductionOfError.zip](https://github.com/bartverdonck/Sitecore-Forms-Extensions/files/3792368/ReproductionOfError.zip)

**Comment by SchelstraeteRuben** [comment] 2020-05-26 12:53
I came across the same issue on SC9.3 with version 3.0 of this module. @bartverdonck is this something that should have been fixed in 3.0? Don't hesitate to contact me if you need help investigating.

**Comment by bartverdonck** [comment] 2020-06-19 13:50
Hi,

I reproduced your scenario on a clean environment with no additional javascript.

I did not encounter the issue.

Maybe @SchelstraeteRuben can help you?

Best Regards,

Bart

**Comment by bartverdonck** [comment] 2020-11-02 12:58
Closing the issue due to no response.

**Closed by bartverdonck** 2020-11-02 12:58 UTC
Labels: could not reproduce
